extends Node2D
signal jugadorSeMueve
signal jugadorHablaConNpc
signal libroEntregado
signal libroAgarrado
signal libroLeido
signal disparo
signal tutorialCompletado
signal jefeDerrotado(nivel)
signal jugadorRecibioDanio(vida)
signal jugadorMuerto
signal coleccionableObtenido
