<<<<<<< HEAD
extends Node2D
signal jugadorSeMovio
signal jugadorHablaConNpc
signal libroEntregado
signal libroAgarrado
signal libroLeido
signal disparoRealizado
signal tutorialCompletado
signal jefeDerrotado
signal jugadorRecibioDanio
signal jugadorMurio
signal coleccionableObtenido